# Generated by Django 3.1.13 on 2021-11-17 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collegeapp', '0001_initial'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfnw',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.student'),
        ),
        migrations.AddField(
            model_name='studentfnw',
            name='wages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeapp.wages'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='leacturare',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userApp.leacturare'),
        ),
    ]
