# Generated by Django 3.1.13 on 2021-11-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField(default=0)),
                ('total_attendance', models.IntegerField(null=True)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateField(default='2017-06-01')),
                ('time', models.TimeField(default='09:00')),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['cr_date'],
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(null=True)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
