# Generated by Django 3.1.13 on 2021-11-17 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collegeapp', '0002_auto_20211117_2158'),
        ('collegestudents', '0001_initial'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='given_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.leacturare'),
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.student'),
        ),
        migrations.AddField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeapp.lecture'),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeapp.lecture'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='given_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.leacturare'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeapp.lecture'),
        ),
    ]
